# .streamlit/secrets.toml

# OpenAI API Key (if you're still using it directly in the app, though it's better to manage through environment or secure config)
OPENAI_API_KEY = "sk-your_openai_api_key_here"

# ClickHouse Database Credentials
CLICKHOUSE_HOST = "localhost"  # e.g., "localhost" or "127.0.0.1" or a remote server IP/hostname
CLICKHOUSE_PORT = 8123                         # Default ClickHouse HTTP/HTTPS port (8123 for HTTP, 8443 for HTTPS)
CLICKHOUSE_USER = "user"   # e.g., "default" or your specific user
CLICKHOUSE_PASSWORD = "123" # Your ClickHouse user's password
CLICKHOUSE_DATABASE = "mydb"   # The database in ClickHouse you want to use, e.g., "default"

# If you are using a secure connection (HTTPS/TLS) to ClickHouse,
# you might need to add a setting for it in your Python code when connecting,
# for example, by setting `secure=True` in clickhouse_connect.get_client().
# The secrets file itself doesn't have a specific flag for this,
# but you can store a boolean here if you want to control it from secrets:
# CLICKHOUSE_SECURE_CONNECTION = true